export const CATEGORY_FIELDS = {
  grocery: [
    { name: 'item', label: 'Item' },
    { name: 'barcode', label: 'Barcode' },
    { name: 'quantity', label: 'Qty', type: 'number' },
    { name: 'sizeValue', label: 'Size Amount', type: 'number' },
    { name: 'size', label: 'Size Unit', type: 'select', options: ['kg (Kilogram)', 'g (Gram)', 'L (Liter)', 'ml (Milliliter)', 'oz (Ounce)', 'lb (Pound)', 'pcs (Pieces)', 'pk (Pack)', 'unit (Unit)'] },
    { name: 'price', label: 'Price', type: 'number' },
    { name: 'store', label: 'Store' },
    { name: 'onSale', label: 'On Sale?', type: 'boolean' },
  ],
  transport: [
    { name: 'from',        label: 'From',             type: 'location' },
    { name: 'destination', label: 'Destination',       type: 'location' },
    { name: 'reason',      label: 'Reason for Travel' },
    { name: 'mode',        label: 'Mode',              type: 'select', options: ['Uber', 'Taxi', 'Train', 'Flight'] },
    { name: 'price',       label: 'Price',             type: 'number' },
    { name: 'barcode',     label: 'Barcode' },
  ],
  lunch: [
    { name: 'foodType', label: 'Food Type' },
    { name: 'store', label: 'Store' },
    { name: 'price', label: 'Price', type: 'number' },
    { name: 'PersonBuyingForName', label: 'Buying For' },
    { name: 'barcode', label: 'Barcode' },
  ],
  garment: [
    { name: 'item', label: 'Item' },
    { name: 'store', label: 'Store' },
    { name: 'price', label: 'Price', type: 'number' },
    { name: 'quantity', label: 'Qty', type: 'number' },
    { name: 'barcode', label: 'Barcode' },
  ],
  furniture: [
    { name: 'item', label: 'Item' },
    { name: 'store', label: 'Store' },
    { name: 'price', label: 'Price', type: 'number' },
    { name: 'quantity', label: 'Qty', type: 'number' },
    { name: 'barcode', label: 'Barcode' },
  ],
  rent: [
    { name: 'price', label: 'Price', type: 'number' },
    { name: 'date', label: 'Date', type: 'date' },
    { name: 'barcode', label: 'Barcode' },
  ],
  cosmetic: [
    { name: 'item', label: 'Item' },
    { name: 'store', label: 'Store' },
    { name: 'price', label: 'Price', type: 'number' },
    { name: 'quantity', label: 'Qty', type: 'number' },
    { name: 'barcode', label: 'Barcode' },
  ],
  takeout: [
    { name: 'item', label: 'Item' },
    { name: 'store', label: 'Store' },
    { name: 'price', label: 'Price', type: 'number' },
    { name: 'PersonBuyingForName', label: 'Buying For' },
    { name: 'barcode', label: 'Barcode' },
  ],
  date: [
    { name: 'restaurant', label: 'Restaurant' },
    { name: 'foodDescription', label: 'Description' },
    { name: 'price', label: 'Price', type: 'number' },
    { name: 'qauntity', label: 'Qty', type: 'number' },
    { name: 'barcode', label: 'Barcode' },
  ],
  other: [
    { name: 'item', label: 'Item' },
    { name: 'store', label: 'Store' },
    { name: 'price', label: 'Price', type: 'number' },
    { name: 'description', label: 'Description' },
    { name: 'barcode', label: 'Barcode' },
  ],
};

export const ALL_CATEGORIES = [
  { key: 'grocery',   label: 'Groceries',  emoji: '🛒' },
  { key: 'transport', label: 'Transport',   emoji: '🚌' },
  { key: 'lunch',     label: 'Lunch',       emoji: '🍔' },
  { key: 'garment',   label: 'Garments',    emoji: '👕' },
  { key: 'furniture', label: 'Furniture',   emoji: '🛋️' },
  { key: 'rent',      label: 'Rent',        emoji: '🏠' },
  { key: 'cosmetic',  label: 'Cosmetics',   emoji: '✨' },
  { key: 'takeout',   label: 'Takeouts',    emoji: '📦' },
  { key: 'date',      label: 'Dates',       emoji: '❤️' },
  { key: 'other',     label: 'Other',       emoji: '•••' },
];
