export const CATEGORY_FIELDS = {
  grocery: [
    { name: 'item', label: 'Item' },
    { name: 'barcode', label: 'Barcode', full: true },
    { name: 'quantity', label: 'Qty', type: 'number' },
    { name: 'size', label: 'Size', type: 'select', options: ['KG', 'Grams', 'Liters', 'ML', 'Units', 'Pieces', 'Pack'] },
    { name: 'sizeValue', label: 'Size Amount', type: 'number' },
    { name: 'price', label: 'Price', type: 'number' },
    { name: 'store', label: 'Store' },
    { name: 'onSale', label: 'On Sale?', type: 'checkbox' },
  ],
  transport: [
    { name: 'from', label: 'From' },
    { name: 'destination', label: 'Destination' },
    { name: 'mode', label: 'Mode', type: 'select', options: ['Uber', 'Taxi', 'Train', 'Flight'] },
    { name: 'price', label: 'Price', type: 'number' },
    { name: 'barcode', label: 'Barcode', full: true },
  ],
  lunch: [
    { name: 'foodType', label: 'Food Type' },
    { name: 'store', label: 'Store' },
    { name: 'price', label: 'Price', type: 'number' },
    { name: 'PersonBuyingForName', label: 'Buying For' },
    { name: 'barcode', label: 'Barcode', full: true },
  ],
  garment: [
    { name: 'item', label: 'Item' },
    { name: 'store', label: 'Store' },
    { name: 'price', label: 'Price', type: 'number' },
    { name: 'quantity', label: 'Qty', type: 'number' },
    { name: 'barcode', label: 'Barcode', full: true },
  ],
  furniture: [
    { name: 'item', label: 'Item' },
    { name: 'store', label: 'Store' },
    { name: 'price', label: 'Price', type: 'number' },
    { name: 'quantity', label: 'Qty', type: 'number' },
    { name: 'barcode', label: 'Barcode', full: true },
  ],
  rent: [
    { name: 'price', label: 'Price', type: 'number' },
    { name: 'date', label: 'Date', type: 'date', full: true },
    { name: 'barcode', label: 'Barcode', full: true },
  ],
  cosmetic: [
    { name: 'item', label: 'Item' },
    { name: 'store', label: 'Store' },
    { name: 'price', label: 'Price', type: 'number' },
    { name: 'quantity', label: 'Qty', type: 'number' },
    { name: 'barcode', label: 'Barcode', full: true },
  ],
  takeout: [
    { name: 'item', label: 'Item' },
    { name: 'store', label: 'Store' },
    { name: 'price', label: 'Price', type: 'number' },
    { name: 'PersonBuyingForName', label: 'Buying For' },
    { name: 'barcode', label: 'Barcode', full: true },
  ],
  date: [
    { name: 'restaurant', label: 'Restaurant' },
    { name: 'foodDescription', label: 'Description', full: true },
    { name: 'price', label: 'Price', type: 'number' },
    { name: 'qauntity', label: 'Qty', type: 'number' },
    { name: 'barcode', label: 'Barcode', full: true },
  ],
  other: [
    { name: 'item', label: 'Item' },
    { name: 'store', label: 'Store' },
    { name: 'price', label: 'Price', type: 'number' },
    { name: 'description', label: 'Description', full: true },
    { name: 'barcode', label: 'Barcode', full: true },
  ],
};
